
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: '{{ doc("main_desc")}}'
      columns:
          - name: id
            description: '{{ doc("table_event2")}}'
            tests:
                - unique
                - not_null
